<a href="https://colab.research.google.com/github/arsingla786/MLFromScratch/blob/main/7label_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib

Using matplotlib backend: agg

In [41]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rajneesh231/retail-insights-a-comprehensive-sales-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'retail-insights-a-comprehensive-sales-dataset' dataset.
Path to dataset files: /kaggle/input/retail-insights-a-comprehensive-sales-dataset

In [42]:
df = pd.read_csv('/root/.cache/kagglehub/datasets/rajneesh231/retail-insights-a-comprehensive-sales-dataset/versions/3/data.csv')

In [43]:
df.columns

Index(['Order No', 'Order Date', 'Customer Name', 'Address', 'City', 'State',
       'Customer Type', 'Account Manager', 'Order Priority', 'Product Name',
       'Product Category', 'Product Container', 'Ship Mode', 'Ship Date',
       'Cost Price', 'Retail Price', 'Profit Margin', 'Order Quantity',
       'Sub Total', 'Discount %', 'Discount $', 'Order Total', 'Shipping Cost',
       'Total'],
      dtype='object')

In [44]:
df.head()

,Order No,Order Date,Customer Name,Address,City,State,Customer Type,Account Manager,Order Priority,Product Name,...,Cost Price,Retail Price,Profit Margin,Order Quantity,Sub Total,Discount %,Discount $,Order Total,Shipping Cost,Total
0,4293-1,02-09-2014,Vivek Sundaresam,"152 Bunnerong Road,Eastgardens",Sydney,NSW,Small Business,Tina Carlton,Critical,UGen Ultra Professional Cordless Optical Suite,...,$156.50,$300.97,$144.47,23.0,"$4,533.52",2%,$194.83,"$4,757.22",$7.18,"$4,291.55"
1,5001-1,24-10-2015,Shahid Hopkins,"438 Victoria Avenue,Chatswood",Sydney,NSW,Corporate,Natasha Song,Medium,Bagged Rubber Bands,...,$0.24,$1.26,$1.02,8.0,$45.20,3%,$0.00,$45.90,$0.70,$46.91
2,5004-1,13-03-2014,Dennis Pardue,"412 Brunswick St,Fitzroy",Melbourne,VIC,Consumer,Connor Betts,Not Specified,TechSavi Cordless Navigator Duo,...,$42.11,$80.98,$38.87,45.0,$873.32,4%,$72.23,$837.57,$7.18,$82.58
3,5009-1,18-02-2013,Sean Wendt,"145 Ramsay St,Haberfield",Sydney,NSW,Small Business,Phoebe Gour,Critical,Artisan Printable Repositionable Plastic Tabs,...,$5.33,$8.60,$3.27,16.0,$73.52,1%,$4.35,$740.67,$6.19,$730.92
4,5010-1,13-09-2014,Christina Vanderzanden,"188 Pitt Street,Sydney",Sydney,NSW,Small Business,Tina Carlton,Not Specified,Pizazz Drawing Pencil Set,...,$1.53,$2.78,$1.25,49.0,$138.46,7%,$5.95,$123.77,$1.34,$125.97

In [45]:
df.columns

Index(['Order No', 'Order Date', 'Customer Name', 'Address', 'City', 'State',
       'Customer Type', 'Account Manager', 'Order Priority', 'Product Name',
       'Product Category', 'Product Container', 'Ship Mode', 'Ship Date',
       'Cost Price', 'Retail Price', 'Profit Margin', 'Order Quantity',
       'Sub Total', 'Discount %', 'Discount $', 'Order Total', 'Shipping Cost',
       'Total'],
      dtype='object')

In [46]:
df = df.drop(['Order No'],axis=1)

In [47]:
df = df.drop(['Order Date','Customer Name','Address'],axis=1)

In [48]:
df['City'].nunique()

2

##One hot encoding using pandas

In [49]:
df = pd.get_dummies(df,columns=['City','State'])

In [50]:
df= pd.get_dummies(df,columns=['Product Container','Customer Type',])

In [51]:
df.columns

Index(['Account Manager', 'Order Priority', 'Product Name', 'Product Category',
       'Ship Mode', 'Ship Date', 'Cost Price', 'Retail Price', 'Profit Margin',
       'Order Quantity', 'Sub Total', 'Discount %', 'Discount $',
       'Order Total', 'Shipping Cost', 'Total', 'City_Melbourne',
       'City_Sydney', 'State_NSW', 'State_VIC', 'Product Container_Jumbo Drum',
       'Product Container_Large Box', 'Product Container_Medium Box',
       'Product Container_Small Box', 'Product Container_Small Pack',
       'Product Container_Wrap Bag', 'Customer Type_Consumer',
       'Customer Type_Corporate', 'Customer Type_Home Office',
       'Customer Type_Small Business'],
      dtype='object')

In [52]:
df.head()

,Account Manager,Order Priority,Product Name,Product Category,Ship Mode,Ship Date,Cost Price,Retail Price,Profit Margin,Order Quantity,...,Product Container_Jumbo Drum,Product Container_Large Box,Product Container_Medium Box,Product Container_Small Box,Product Container_Small Pack,Product Container_Wrap Bag,Customer Type_Consumer,Customer Type_Corporate,Customer Type_Home Office,Customer Type_Small Business
0,Tina Carlton,Critical,UGen Ultra Professional Cordless Optical Suite,Office Supplies,Regular Air,04-09-2014,$156.50,$300.97,$144.47,23.0,...,False,False,False,True,False,False,False,False,False,True
1,Natasha Song,Medium,Bagged Rubber Bands,Office Supplies,Regular Air,26-10-2015,$0.24,$1.26,$1.02,8.0,...,False,False,False,False,True,False,False,True,False,False
2,Connor Betts,Not Specified,TechSavi Cordless Navigator Duo,Office Supplies,Regular Air,13-03-2014,$42.11,$80.98,$38.87,45.0,...,False,False,False,True,False,False,True,False,False,False
3,Phoebe Gour,Critical,Artisan Printable Repositionable Plastic Tabs,Office Supplies,Regular Air,20-02-2013,$5.33,$8.60,$3.27,16.0,...,False,False,False,False,False,True,False,False,False,True
4,Tina Carlton,Not Specified,Pizazz Drawing Pencil Set,Office Supplies,Express Air,17-09-2014,$1.53,$2.78,$1.25,49.0,...,False,False,False,False,False,True,False,False,False,True

In [53]:
df.drop(['Account Manager'],axis=1)

,Order Priority,Product Name,Product Category,Ship Mode,Ship Date,Cost Price,Retail Price,Profit Margin,Order Quantity,Sub Total,...,Product Container_Jumbo Drum,Product Container_Large Box,Product Container_Medium Box,Product Container_Small Box,Product Container_Small Pack,Product Container_Wrap Bag,Customer Type_Consumer,Customer Type_Corporate,Customer Type_Home Office,Customer Type_Small Business
0,Critical,UGen Ultra Professional Cordless Optical Suite,Office Supplies,Regular Air,04-09-2014,$156.50,$300.97,$144.47,23.0,"$4,533.52",...,False,False,False,True,False,False,False,False,False,True
1,Medium,Bagged Rubber Bands,Office Supplies,Regular Air,26-10-2015,$0.24,$1.26,$1.02,8.0,$45.20,...,False,False,False,False,True,False,False,True,False,False
2,Not Specified,TechSavi Cordless Navigator Duo,Office Supplies,Regular Air,13-03-2014,$42.11,$80.98,$38.87,45.0,$873.32,...,False,False,False,True,False,False,True,False,False,False
3,Critical,Artisan Printable Repositionable Plastic Tabs,Office Supplies,Regular Air,20-02-2013,$5.33,$8.60,$3.27,16.0,$73.52,...,False,False,False,False,False,True,False,False,False,True
4,Not Specified,Pizazz Drawing Pencil Set,Office Supplies,Express Air,17-09-2014,$1.53,$2.78,$1.25,49.0,$138.46,...,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Critical,Artisan Hi-Liter Smear-Safe Highlighters,Office Supplies,Regular Air,06-11-2016,$2.98,$5.84,$2.86,35.0,$115.40,...,False,False,False,False,True,False,False,True,False,False
4996,Not Specified,Smiths Colored Interoffice Envelopes,Office Supplies,Regular Air,18-12-2015,$19.83,$30.98,$11.15,49.0,"$1,999.69",...,False,False,False,False,True,False,False,False,False,True
4997,Low,Laser DVD-RAM discs,Furniture,Regular Air,30-09-2016,$20.18,$35.41,$15.23,19.0,$929.40,...,False,False,False,False,True,False,True,False,False,False
4998,Not Specified,Artisan 479 Labels,Office Supplies,Regular Air,20-06-2016,$1.59,$2.61,$1.02,23.0,$66.54,...,False,False,False,False,False,True,False,True,False,False
4999,Low,Binder Posts,Office Supplies,Regular Air,14-08-2015,$3.50,$5.74,$2.24,31.0,$213.34,...,False,False,False,True,False,False,True,False,False,False

In [54]:
df['Ship Mode'].unique()

array(['Regular Air', 'Express Air', 'Delivery Truck'], dtype=object)

In [55]:
df['Order Priority'].unique()

array(['Critical', 'Medium', 'Not Specified', 'Low', 'High'], dtype=object)

##Ordinal encoding

In [56]:
#ship mode and order priority need to me ordinal encoded

In [57]:
#train test split before ordinal encoding
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(['Profit Margin'],axis=1),df['Profit Margin'],test_size=0.2,random_state=42)

In [58]:
#  ship mode -> order  => express air > regular air > delivery truck
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Delivery Truck','Regular Air','Express Air']])
X_train['Ship Mode'] = oe.fit_transform(X_train[['Ship Mode']])
X_test['Ship Mode'] = oe.transform(X_test[['Ship Mode']])

In [59]:
#order priority -> 'Not Specified','Low','Medium ,'High', 'Critical'

In [60]:
oe = OrdinalEncoder(categories=[['Not Specified','Low','Medium' ,'High', 'Critical']])
X_train['Order Priority'] = oe.fit_transform(X_train[['Order Priority']])
X_test['Order Priority'] = oe.transform(X_test[['Order Priority']])

In [67]:
X_train

,Account Manager,Order Priority,Product Name,Product Category,Ship Mode,Ship Date,Cost Price,Retail Price,Order Quantity,Sub Total,...,Product Container_Jumbo Drum,Product Container_Large Box,Product Container_Medium Box,Product Container_Small Box,Product Container_Small Pack,Product Container_Wrap Bag,Customer Type_Consumer,Customer Type_Corporate,Customer Type_Home Office,Customer Type_Small Business
4227,Yvette Biti,0.0,1726 Digital Answering Machine,Furniture,2.0,29-10-2013,$8.82,$20.99,7.0,$30.86,...,False,True,False,False,False,False,False,False,True,False
4676,Nicholas Fernandes,0.0,Smiths Metal Binder Clips,Office Supplies,2.0,11-09-2015,$1.60,$2.62,30.0,$283.84,...,False,False,False,False,False,True,False,True,False,False
800,Phoebe Gour,1.0,Artisan Durable Poly Binders,Technology,1.0,23-10-2013,$3.37,$5.53,29.0,$239.20,...,False,False,False,True,False,False,False,False,True,False
3671,Connor Betts,0.0,Steady 52201 APSCO Electric Pencil Sharpener,Office Supplies,1.0,16-05-2013,$16.80,$40.97,22.0,"$1,639.30",...,False,False,False,False,True,False,False,False,True,False
4193,Mihael Khan,3.0,"TypeRight Top-Opening Peel & Seel Envelopes,...",Office Supplies,1.0,05-12-2016,$21.56,$35.94,40.0,"$2,442.96",...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4426,Tina Carlton,4.0,Artisan 478 Labels,Office Supplies,2.0,12-12-2016,$3.14,$4.91,41.0,$65.32,...,False,False,False,False,False,True,False,False,True,False
466,Samantha Chairs,1.0,Binder Posts,Technology,1.0,30-06-2014,$3.50,$5.74,46.0,$263.90,...,False,False,False,True,False,False,False,True,False,False
3092,Preston Senome,0.0,"TypeRight Side-Opening Peel & Seel Envelopes,...",Office Supplies,1.0,31-05-2013,$21.56,$35.94,6.0,"$4,796.50",...,False,False,False,False,False,True,False,False,False,True
3772,Natasha Song,2.0,Artisan 478 Labels,Office Supplies,1.0,23-12-2016,$3.14,$4.91,41.0,$32.86,...,False,False,False,False,False,True,False,True,False,False
860,Tina Carlton,2.0,Artisan 481 Labels,Office Supplies,1.0,30-10-2013,$1.94,$3.08,32.0,$126.28,...,False,False,False,True,False,False,False,False,False,True