<a href="https://colab.research.google.com/github/arsingla786/MLFromScratch/blob/main/BackPropagationInANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','resume_score','lpa'])

In [ ]:
df

   cgpa  resume_score  lpa
0     8             8    4
1     7             9    5
2     6            10    6
3     5            12    7

In [ ]:
#this function initializes 9 random values for 6 weights and 3 biases
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters={}
  L=len(layer_dims)
  for l in range(1,L):
    parameters['w'+str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1

    parameters['b'+str(l)] = np.zeros((layer_dims[l],1))

  return parameters

In [ ]:
initialize_parameters([2,2,1])
#neurons in each layer ->2,2,1

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
def linear_forward(A_prev,W,b):
  Z= np.dot(W.T,A_prev)+b
  #T means transpose
  return Z

In [ ]:
#forward propagation
def L_layer_forward(X,parameters):
  A=X
  L=len(parameters)//2
  for l in range(1,L+1):
    A_prev = A
    wl = parameters['w'+str(l)]
    bl = parameters['b'+str(l)]
    A = linear_forward(A_prev,wl,bl)
  return A,A_prev

In [ ]:
#predict
X = df[['cgpa','resume_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

parameters = initialize_parameters([2,2,1])
y_hat,A1=L_layer_forward(X,parameters)
y_hat = y_hat[0][0]
y_hat

np.float64(0.32000000000000006)

In [ ]:
#find loss
loss = (y-0.32)**2
loss

np.float64(13.5424)

In [ ]:
def update_parameters(parameters, y, y_hat, A1, X):

    parameters['w2'][0][0] = parameters['w2'][0][0] + (0.001 * 2 * (y - y_hat) * A1[0][0])
    parameters['w2'][1][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat) * A1[1][0])
    parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * 2 * (y - y_hat))

    parameters['w1'][0][0] = parameters['w1'][0][0] + (0.001 * 2 * (y - y_hat) * parameters['w2'][0][0] * X[0][0])
    parameters['w1'][0][1] = parameters['w1'][0][1] + (0.001 * 2 * (y - y_hat) * parameters['w2'][0][0] * X[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat) * parameters['w2'][0][0])

    parameters['w1'][1][0] = parameters['w1'][1][0] + (0.001 * 2 * (y - y_hat) * parameters['w2'][1][0] * X[0][0])
    parameters['w1'][1][1] = parameters['w1'][1][1] + (0.001 * 2 * (y - y_hat) * parameters['w2'][1][0] * X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat) * parameters['w2'][1][0])

In [ ]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'w1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'w2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

In [ ]:
epochs = 5

for i in range(epochs):

    Loss = []

    for j in range(df.shape[0]):

        X = df[['cgpa', 'resume_score']].values[j].reshape(2,1)  # Shape (no of features, no. of training example)

        y = df[['lpa']].values[j][0]

        # Parameter initialization

        y_hat, A1 = L_layer_forward(X, parameters)

        y_hat = y_hat[0][0]

        update_parameters(parameters, y, y_hat, A1, X)

        Loss.append((y - y_hat) ** 2)

    print('Epoch - ', i, 'Loss - ', np.array(Loss).mean())

Epoch -  0 Loss -  25.35559520553253
Epoch -  1 Loss -  17.9214604627527
Epoch -  2 Loss -  8.660201551051749
Epoch -  3 Loss -  2.766384943293067
Epoch -  4 Loss -  1.2405317492813641

In [ ]:
parameters

{'w1': array([[0.27712863, 0.40248484],
        [0.28971117, 0.42627569]]),
 'b1': array([[0.02927392],
        [0.03147967]]),
 'w2': array([[0.43121093],
        [0.5030264 ]]),
 'b2': array([[0.11913402]])}

In [ ]:
#using keras library for the same
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
df = pd.DataFrame([[8,8,4],[7,9,4],[6,10,6],[5,12,7]],columns=['cgpa','resume_score','lpa'])

In [ ]:
df

   cgpa  resume_score  lpa
0     8             8    4
1     7             9    4
2     6            10    6
3     5            12    7

In [ ]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[0.13919032, 0.5145086 ],
        [1.1643759 , 0.53397346]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.0315003 ],
        [-0.45113277]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=100,verbose=1,batch_size=1)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.9493
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.0643
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 94.1313
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 93.2104
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 92.4485
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 91.6154
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.7604
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 89.9166
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 89.1421
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 88.3350
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 87.5691
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.7595
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.9391
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 85.2577
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 84.4630
Epoch 16/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 83.7469
Epoch 17/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 83.0731
Epoch 18/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 82.2629
Epoch 19/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 81.6217
Epoch 20/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.8453
Epoch 21/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 80.1855
Epoch 22/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 79.5403
Epoch 23/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.8403
Epoch 24/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 78.2143
Epoch 25/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 77.5275
Epoch 26/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 76.8423
Epoch 27/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 76.2333
Epoch 28/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75.6111
Epoch 29/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 74.9764
Epoch 30/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 74.3233
Epoch 31/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 73.7504
Epoch 32/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 73.1588
Epoch 33/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.5224
Epoch 34/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.9853
Epoch 35/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 71.3643
Epoch 36/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 70.8313
Epoch 37/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 70.2239
Epoch 38/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 69.6212
Epoch 39/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 69.1161
Epoch 40/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 68.5580
Epoch 41/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.0050
Epoch 42/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 67.4552
Epoch 43/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.9879
Epoch 44/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.4070
Epoch 45/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 65.8853
Epoch 46/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 65.4404
Epoch 47/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.8700
Epoch 48/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.3690
Epoch 49/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 63.9387
Epoch 50/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 63.4081
Epoch 51/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 62.9470
Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 62.4352
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 61.9472
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 61.5284
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 61.0274
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 60.5483
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 60.1132
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 59.6734
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.2557
Epoch 60/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 58.7892
Epoch 61/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 58.3513
Epoch 62/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 57.9722
Epoch 63/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.5068
Epoch 64/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.1054
Epoch 65/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.6614
Epoch 66/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 56.2455
Epoch 67/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.8805
Epoch 68/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.4440
Epoch 69/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 55.1066
Epoch 70/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 54.6540
Epoch 71/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 54.2517
Epoch 72/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 53.9252
Epoch 73/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 53.4717
Epoch 74/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 53.1369
Epoch 75/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 52.7156
Epoch 76/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 52.3561
Epoch 77/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 51.9944
Epoch 78/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 51.6323
Epoch 79/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 51.3139
Epoch 80/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 50.9660
Epoch 81/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 50.6001
Epoch 82/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 50.1971
Epoch 83/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 49.8638
Epoch 84/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 49.5409
Epoch 85/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 49.1710
Epoch 86/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 48.8754
Epoch 87/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 48.5115
Epoch 88/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 48.1800
Epoch 89/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 47.8506
Epoch 90/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 47.5511
Epoch 91/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.1859
Epoch 92/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 46.9177
Epoch 93/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 46.5909
Epoch 94/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 46.2564
Epoch 95/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 45.9207
Epoch 96/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 45.6689
Epoch 97/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 45.3652
Epoch 98/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 45.0299
Epoch 99/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 44.7580
Epoch 100/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 44.4165

In [ ]:
model.get_weights()

[array([[-0.4118541 ,  0.14943248],
        [ 0.6305802 ,  0.18057168]], dtype=float32),
 array([-0.548804  , -0.36349398], dtype=float32),
 array([[-0.5758517 ],
        [-0.01558945]], dtype=float32),
 array([0.6490926], dtype=float32)]

##Classification Problem

In [ ]:
#use activation -> sigmoid
#use loss function -> binary_cross_entropy